# Generated by Django 6.0.2 on 2026-03-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndYearReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('project_overview', models.TextField()),
                ('children_impacted', models.TextField()),
                ('other_individuals_impacted', models.TextField()),
                ('long_term_impact', models.TextField()),
                ('hope_impact', models.TextField()),
                ('remaining_funds', models.TextField()),
                ('budget', models.TextField()),
                ('what_worked_well', models.TextField()),
                ('challenges', models.TextField()),
                ('story_1', models.TextField()),
                ('story_2', models.TextField(blank=True)),
                ('future_funding', models.TextField()),
                ('video_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HopeGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('superintendent_first_name', models.CharField(max_length=100)),
                ('superintendent_last_name', models.CharField(max_length=100)),
                ('superintendent_phone', models.CharField(max_length=20)),
                ('superintendent_email', models.EmailField(max_length=254)),
                ('primary_contact_first_name', models.CharField(max_length=100)),
                ('primary_contact_last_name', models.CharField(max_length=100)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('address_street', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=2)),
                ('address_zip', models.CharField(max_length=10)),
                ('grant_amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_summary', models.TextField()),
                ('needs_statement', models.TextField()),
                ('impact_children', models.TextField()),
                ('impact_other_individuals', models.TextField()),
                ('impact_long_term', models.TextField()),
                ('collaboration', models.TextField()),
                ('budget', models.TextField()),
                ('success', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidYearReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('progress_update', models.TextField()),
                ('unexpected_difficulties', models.TextField()),
                ('successes', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
