# Generated by Django 6.0.2 on 2026-04-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndYearReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('project_overview', models.TextField()),
                ('children_impacted', models.TextField()),
                ('other_individuals_impacted', models.TextField()),
                ('long_term_impact', models.TextField()),
                ('hope_impact', models.TextField()),
                ('remaining_funds', models.TextField()),
                ('budget', models.TextField()),
                ('what_worked_well', models.TextField()),
                ('challenges', models.TextField()),
                ('story_1', models.TextField()),
                ('story_2', models.TextField(blank=True)),
                ('future_funding', models.TextField()),
                ('video_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('intro_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('footer_link', models.URLField(blank=True)),
                ('footer_link_label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HopeGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('superintendent_first_name', models.CharField(max_length=100)),
                ('superintendent_last_name', models.CharField(max_length=100)),
                ('superintendent_phone', models.CharField(max_length=20)),
                ('superintendent_email', models.EmailField(max_length=254)),
                ('primary_contact_first_name', models.CharField(max_length=100)),
                ('primary_contact_last_name', models.CharField(max_length=100)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('address_street', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=2)),
                ('address_zip', models.CharField(max_length=10)),
                ('grant_amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_summary', models.TextField()),
                ('needs_statement', models.TextField()),
                ('impact_children', models.TextField()),
                ('impact_other_individuals', models.TextField()),
                ('impact_long_term', models.TextField()),
                ('collaboration', models.TextField()),
                ('budget', models.TextField()),
                ('success', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidYearReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_district', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('progress_update', models.TextField()),
                ('unexpected_difficulties', models.TextField()),
                ('successes', models.TextField()),
                ('additional_comments', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EndYearComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endyearreport')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hopegrantapplication')),
            ],
        ),
        migrations.CreateModel(
            name='MidYearComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.midyearreport')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('tel', 'Phone Number'), ('decimal', 'Decimal Number')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.form')),
                ('school_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.schooldistrict')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.form')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.submission')),
            ],
        ),
    ]
