# Generated by Django 6.0.2 on 2026-04-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endyearcomment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='midyearcomment',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ApplicationComment',
        ),
        migrations.DeleteModel(
            name='HopeGrantApplication',
        ),
        migrations.DeleteModel(
            name='EndYearComment',
        ),
        migrations.DeleteModel(
            name='EndYearReport',
        ),
        migrations.DeleteModel(
            name='MidYearComment',
        ),
        migrations.DeleteModel(
            name='MidYearReport',
        ),
    ]
