# Generated by Django 6.0.2 on 2026-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_endyearcomment_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
