# Generated by Django 6.0.2 on 2026-04-25 05:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_uploaded_by_form_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[app.models.validate_file_size]),
        ),
    ]
