# Generated by Django 6.0.2 on 2026-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
