# Generated by Django 6.0.2 on 2026-04-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignature',
            name='submission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersignature',
            name='submitted_by',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
