# Generated by Django 6.0.2 on 2026-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usersignature_submission_usersignature_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignature',
            name='submission',
            field=models.IntegerField(),
        ),
    ]
